version: '3.9'

services:
  web:
    build: ./taskapi
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./taskapi:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
